sudo: false
install:
     - 'if [ ! -d $HOME/.rakudobrew ]; then git clone https://github.com/tadzik/rakudobrew.git $HOME/.rakudobrew; fi'
     - which perl6 || rakudobrew build moar 2017.01
     - which zef || rakudobrew build-zef
     - zef --depsonly install . || true
script:
  - zef test .
cache:
  directories:
    - $HOME/.rakudobrew
env:
  global:
    - PATH=$PATH:$HOME/.rakudobrew/bin
