language: perl6
os:
  - osx
  - linux
addons:
  apt:
    sources:
      - ppa:jonathonf/perl6
    packages:
      - perl6
before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install rakudo-star; fi
script:
  - prove -perl6 t/*
