language: perl6
os:
  - osx
  - linux
addons:
  apt:
    sources:
      - ppa:jonathonf/perl6
    packages:
      - perl6
before_install:
  - [[ "$TRAVIS_OS_NAME" == "osx" ]] && brew update
  - [[ "$TRAVIS_OS_NAME" == "osx" ]] && brew install rakudo-star
script:
  - prove -perl6 t/*
